config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  devise_scope :user do
    root to: 'devise/sessions#new'
    get :'/users/sign_out', to: 'devise/sessions#destroy', as: :logout
  end

  namespace :admin do
    get    :'/users',           to: 'users#index',  as: :users
    get    :'/user/:id',        to: 'users#show',   as: :show_user,   constraints: { id: /[0-9]+/ }
    get    :'/edit/user/:id',   to: 'users#edit',   as: :edit_user,   constraints: { id: /[0-9]+/ }
    patch  :'/update/user/:id', to: 'users#update', as: :update_user, constraints: { id: /[0-9]+/ }
  end

  namespace :api do
    namespace :v1 do
      post :'/user_tokens', to: 'user_tokens#create', as: :user_tokens
      get :'/address/:zip_code', to: 'addresses#show', as: :addresses, constraints: { zip_code: /[0-9\-]+/ }
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  extend Enumerize
  enumerize :role, scope: true, in: {
    admin:    :admin,
    consumer: :consumer,
    pending: :pending,
    blocked:  :blocked
  }, default: :consumer


  has_many :user_tokens
  has_and_belongs_to_many :addresses


  validates_uniqueness_of :email
  validates_presence_of :name, :email, :role

  def admin?
    self.role.admin? rescue false
  end

  def consumer?
    self.role.consumer? rescue false
  end

  def pending?
    self.role.pending? rescue false
  end

  def blocked?
    self.role.blocked? rescue false
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    load_and_authorize_resource

    def show
      respond_to do |format|
        format.html { render :show }
      end
    end

    def index
      @q = User.accessible_by(current_ability, :index).ransack(params[:q])
      @users = @q.result(distinct: true).page(page).per(per_page)

      respond_to do |format|
        format.html { render :index }
      end
    end

    def edit
      respond_to do |format|
        format.html { render :edit }
      end
    end

    def update
      respond_to do |format|
        if @user.update(user_params)
          format.html { redirect_to admin_users_path, flash: default_flash_success_message(:update) }
        else
          format.html { render :edit, flash: default_flash_error_message(:update) }
        end
      end
    end

    private

    def user_params
      p = params.require(:user).permit(
        :name,
        :email,
        :password,
        :password_confirmation
      )
      p = p.except(:password, :password_confirmation) if p[:password].blank?
      return p
    end
  end
end

app/views/admin/users/edit.html.erb
<div class="card">
  <div class="card-action">
    <%= t('activerecord.models.user.one') %>
  </div>
  <div class="card-content">
    <%= render 'devise/shared/error_messages', resource: @user %>
    <%= form_for(@user, url: admin_update_user_path(@user)) do |f| %>
      <% if @current_user.admin? %>
        <div class="row m-b-0">
          <div class="input-field col s3">
            <%= f.select :role, User.role.options %>
            <%= f.label :role %>
          </div>
        </div>
      <% end %>
      <div class="row m-b-0">
        <div class="input-field col s12 m3">
          <%= f.text_field :name %>
          <%= f.label :name %>
        </div>
        <div class="input-field col s12 m3">
          <%= f.email_field :email %>
          <%= f.label :email %>
        </div>
        <div class="input-field col s12 m3">
          <%= f.password_field :password, placeholder: t('controllers.devise/registrations.new.characters_at_least', characters: @minimum_password_length) %>
          <%= f.label :password %>
        </div>
        <div class="input-field col s12 m3">
          <%= f.password_field :password_confirmation, placeholder: t('controllers.devise/registrations.new.characters_at_least', characters: @minimum_password_length) %>
          <%= f.label :password_confirmation %>
        </div>
      </div>
      <div class="row m-b-0">
        <div class="input-field col s12">
          <%= f.button t('actions.update'), class: 'waves-effect waves-light btn', style: 'width: 100%;' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class="card">
  <div class="card-action">
    <%= t('activerecord.models.user.other') %>
  </div>
  <div class="card-content">
    <%= paginate @users %>
    <table class="striped centered responsive-table">
      <thead>
        <tr>
          <th><%= sort_link(@q, :name,       :name) %></th>
          <th><%= sort_link(@q, :email,      :email) %></th>
          <th><%= sort_link(@q, :role,       :role) %></th>
          <th><%= sort_link(@q, :created_at, :created_at) %></th>
          <th><%= sort_link(@q, :updated_at, :updated_at) %></th>
          <th><%= t('actions.title') %></th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td>
              <div class="table-primary-info">
                <%= user.name %>
              </div>
            </td>
            <td>
              <div class="table-primary-info">
                <%= user.email %>
              </div>
            </td>
            <td>
              <div class="table-primary-info">
                <%= user.role_text %>
              </div>
            </td>
            <td>
              <div class="table-primary-info">
                <%= l(user.created_at) %>
              </div>
            </td>
            <td>
              <div class="table-primary-info">
                <%= l(user.updated_at) %>
              </div>
            </td>
            <td>
              <% if can? :edit, user %>
                <%= link_to t('actions.edit'), admin_edit_user_path(user), class: 'waves-effect waves-light' %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= paginate @users %>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="card">
  <div class="card-action">
    User: <%= @user.name %>
  </div>
  <div class="card-content">
    <p>Email: <%= @user.email %></p>
    <p>Permissão: <%= @user.role_text %></p>
    <p>Created At<%= l(@user.created_at) %></p>
    <p>Updated At<%= l(@user.updated_at) %></p>
    <% if can? :edit, @user %>
      <%= link_to "Edit", admin_edit_user_path(@user), class: 'waves-effect waves-light' %>
    <% end %>
  </div>
</div>